<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog modal-lg">
	  <!-- Modal content-->
		<div id="myModal1" class="modal-content purple-border">
		    <div class="col-lg-12 "><br><br>
		      <h4 class="text-center modal-title products-title morado"><b>{{ trans('welcome.register.terms_conditions') }}</b></h4>
		    </div>
		    <div id="m-terms" class="modal-body overflow-modal">
		    	<div class="container">
		    		<div id="divToPrint" class="col-lg-12">
		    			@if (session()->get('lang_id')->short_name == "ENG")
			    		<div class="row">
				    		<div class="col">
				    			<p class="sansserif">Having read and understood the Distributor’s Manual, I hereby state my interest in becoming an Independent Distributor of OMNILIFE and SEYTÚ COSMÉTICA in the UNITED STATES OF AMERICA, pursuant to the following agreement:</p>
				    			<p class="sansserif">INDEPENDENT DISTRIBUTION AGREEMENT ENTERED INTO BY OMNIL- IFE USA, INC., hereinafter REFERRED TO AS "OMNILIFE," AND THE PERSON INTERESTED IN BECOMING AN INDEPENDENT DISTRIBUTOR, HEREINAFTER REFERRED TO AS THE "DISTRIBUTOR,” WHO WILL JOINTLY BE REFERRED TO AS THE "PARTIES," AND WHO AGREE TO SUBMIT TO THE FOLLOWING STATEMENTS AND CLAUSES: <br>
			    				STATEMENTS <br>	
								I. OMNILIFE declares that:<br>
								a) It is a legally established company that complies with applicable law.
								b) Its purpose, amongst other activities, is to market a number of different
								products, hereinafter referred to as the "Products." <br>
								c) It has the necessary licenses and permits to carry out its business activity. <br>
								d) Because it a multi-level direct sales company pursuant to the law, it is
								interested in having the DISTRIBUTOR market its Products in a non-exclusive
								manner. <br>
								e) Its registered address is Legacy Town Center II, 6900 North Dallas Parkway,
								Suite 870, Plano, Texas, 75024. <br>
								II. The DISTRIBUTOR declares that he/she: <br>
								a) Is a salesperson with the necessary resources, experience, and know-how to carry out this activity. <br>
								b) Is interested in becoming an Independent Distributor of OMNILIFE. <br>
								c) Performs his/her commercial activities in an independent, non-subordinate,
								non-exclusive manner, without prejudice to other activities that he/she may
								perform at this time and which may continue in the future. <br>
								d) Is registered as a merchant with the relevant authority, to issue the support-ing documents. <br>
								e) Has received to his/her satisfaction the Distributor’s Manual, which is an integral part of the present agreement, and equally declares to have fully read
								and understood said document in its entirety, agreeing to abide by its
								provisions. <br>
								f) Has provided a correct and valid address and contact information in the
								preceding introduction form, as is the rest of the contact information included
								therein. <br>
								Based on the foregoing, both Parties agree to be bound by the following: <br>
								CLAUSES <br>
								FIRST.- The DISTRIBUTOR may distribute the Products within the United States and its territories and in those countries in which Omnilife has a
								presence, provided that the products to be distributed are purchased in the same country in which they will be resold, and that the DISTRIBUTOR has the
								necessary authorization to do so, in accordance with local law. <br>
								In his/her capacity as DISTRIBUTOR, he/she has: I) The right to certain discount levels as a result of the personal purchase volume; II) A profit based on the difference between the discounted price at which the Products are acquired and the resale price at which they are sold; and (III) Earnings based on the purchases made by the distributors sponsored by him/her, and therefore 
								</p>
				    		</div>
				    		<div class="col">
				    			<p class="sansserif">
				    				considered - for the purposes of this agreement - as part of the DISTRIBU-TOR’S distribution network. These benefits are pursuant to the information included in the Distributor’s Manual, which represents an annex to this agree-ment. <br>
				    				SECOND.- Due to the multi-level and earnings structure of the business, the DISTRIBUTOR may – in accordance with this structure and in any country in which OMNILIFE has a presence - buy products, resell them, and sponsor new people who are interested in distributing them, obtaining the earnings that
									correspond in each case. The payment of said earnings will be channeled	through OMNILIFE, to which the DISTRIBUTOR grants free mandate without
									representation so that the company may deliver the earnings generated by the DISTRIBUTOR and processed by OMNILIFE on his/her behalf. The DISTRIBUTOR will comply with any and all tax obligations that may apply. <br>
									THIRD.- In the event that the DISTRIBUTOR does not have the necessary tax registration, records, receipts and/or authorizations demanded by the local tax
									authorities for the performance of the commercial activities agreed to herein, OMNILIFE will be unable to complete payment of any earnings to which the
									DISTRIBUTOR has a right until the his/her tax situation is resolved. Nevertheless, OMNILIFE will have the power - at its own discretion – to set up a way to defer payment or channel payment to the DISTRIBUTOR in a different way, after deducting any applicable charges and taxes. It may credit the DISTRIBUTOR’S account with which he/she makes direct purchases, as established in the Distributor’s Manual. Payment may also be handled otherwise, as the case
									may be. <br>
									FOURTH.- OMNILIFE makes a commitment to sell the DISTRIBUTOR the Products that he or she requires, provided that OMNILIFE has them in stock. The Products will always be delivered to the DISTRIBUTOR in perfect condition and in accordance with applicable sanitary standards and regulations. <br>
									FIFTH.- The DISTRIBUTOR must pay his or her purchases in full at the moment of placing the order, and may use any of the payment options accepted by OMNILIFE. <br>
									SIXTH.- The product prices will be set by OMNILIFE according to the price list in effect at the moment the Products are purchased by the DISTRIBUTOR. OMNILIFE may suggest the resale price to the general public of the Products the DISTRIBUTOR purchases to this end. <br>
									SEVENTH.- The risk regarding the storage and loss of the Products will be assumed by their owner; that is, by OMNILIFE until the company turns them over to the DISTRIBUTOR by virtue of a sale, and by the DISTRIBUTOR from the moment he/she receives them due to a purchase. <br>
									EIGHTH.- Because the DISTRIBUTOR manages his/her own business and personal and professional resources, the DISTRIBUTOR may employ his/her own sales and distribution strategies; however, OMNILIFE may suggest
									marketing plans to be used to market the Products. <br>
									NINTH.- All the expenses generated by the DISTRIBUTOR during the distribution of the Products, such as tax payments, transportation costs, office supplies or any other, will be his/her responsibility. <br>
									TENTH.- In relation to all the expenses associated with shipping and handling, and as the ongoing advertising and marketing costs related to the Products
									being sold through OMNILIFE’s multi-level distribution system, the PARTIES agree that OMNILIFE may establish certain fees, and that – as is the case with the product prices - they will be the responsibility of the DISTRIBUTOR once they are defined. <br>
				    			</p>
				    		</div>
						</div>
						<div class="row">
							<div class="col">
								<p class="sansserif">
									ELEVENTH.- If the DISTRIBUTOR, in the course of marketing the Products to his/her customers, finds that any of them is interested in distributing them as
									well, he/she may introduce them to OMNILIFE and they can apply to become distributors and sign the corresponding Distribution Agreement; this action
									does not entail any payment from OMNILIFE to the DISTRIBUTOR. In the event that they are accepted as new distributors, they will become part of the
									first DISTRIBUTOR’S distribution network. <br>
									TWELVETH.- The rights and obligations of the DISTRIBUTOR with respect to this agreement may not be transferred without the express, prior, and written
									consent of OMNILIFE. <br>
									THIRTEENTH.- The DISTRIBUTOR will conduct him/herself with honesty and will not engage in misleading or unethical business practices; therefore, it will
									be the DISTRIBUTOR’S obligation to comply at all times with any and all laws that may be applicable as a result of his/her professional activity. <br>
									FOURTEENTH.- The Distributor must respect all intellectual property rights and copyrights of the companies in the OMNILIFE GROUP and its subsidiaries.
									The DISTRIBUTOR may not use the name of any of the companies in the OMNILIFE GROUP, its registered trademarks, or any of its distinctive signs
									being used in the commercialization of the Products, in any advertising medium, electronic media, business cards, posters, flyers, brochures, vehicles,
									checks, or letterheads, without the prior written consent of OMNILIFE. <br>
									FIFTEENTH.- Under no circumstances may the DISTRIBUTOR present him/herself as an employee, franchisee, representative or agent of OMNILIFE,
									or of any other OMNILIFE distributor. Accordingly, neither party will have any obligation to the other, as a representative, agent, or otherwise. Therefore, if the DISTRIBUTOR should present him/herself as occupying any of these roles, he/she shall be liable for any damages caused to OMNILIFE or a third party. <br>
									SIXTEENTH.- This agreement will have an indefinite duration as long as the provisions established in the Distributor’s Manual are adhered to. However,
									either party will be able to unilaterally terminate this agreement - at any time and for any reason - by giving written notice 30 calendar days in advance,
									without liability for the party who has requested said termination. Once the corresponding period has transpired, the agreement will be canceled, and
									neither party shall have any subsequent rights in regards to the other except for the liquidation of outstanding debts. <br>
									SEVENTEENTH.- In the event that the DISTRIBUTOR should fail to comply with any of its obligations under this agreement or the Distributor’s Manual,
									OMNILIFE will have the power to terminate the agreement, with said termination taking place automatically once the DISTRIBUTOR receives a written
									communication affirming this clause, without prejudice to any legal actions OMNILIFE may carry out against the DISTRIBUTOR, who has the right to do
									the same under equal terms. With the termination of this agreement, neither party shall have any subsequent rights in regards to the other except for the liquidation of outstanding debts. <br>
									EIGHTEENTH.- Pursuant to the type of business, the DISTRIBUTOR agrees that OMNILIFE has the right to modify at any time the Distributor’s Manual –
									which it has made available to the DISTRIBUTOR in electronic as well as written form. These modifications will be made available to the DISTRIBUTOR on the notice boards of the Distribution Centers and on OMNILIFE’S website, which the DISTRIBUTOR knows how to access, and will be published prior to their implementation. In the event the DISTRIBUTOR does not agree with a particular modification, he/she will be entitled to terminate his/her agreement by sending a simple message to OMNILIFE. If there is no statement opposing the
									changes made by the DISTRIBUTOR during the allotted time, the amendments to the Distributor’s Manual will be considered approved and accepted, and will
									become enforceable. <br>
									NINETEENTH.- The DISTRIBUTOR is not obligated to purchase certain Products or do so with any type of frequency, nor is he/she subject to any
									particular business hours for the distribution of the Products; furthermore, he/she shall not be subject to the authority or instructions of OMNILIFE employ-
									ees, nor be held accountable by them in the performance of his/her activities, except those activities pursuant to the nature of this agreement. <br>
									TWENTIETH.-.- The DISTRIBUTOR may authorize another person to participate in the distribution of OMNILIFE Products under his/her same agreement; this person, who assumes the role of Co-distributor, will participate directly in the purchase and sale of the Products, as well as in the operation and marketing of the Independent Business. Being appointed Co-distributor implies <br>
								</p>
							</div>
							<div class="col">
								<p class="sansserif">
									becoming the beneficiary of all the rights and obligations of the DISTRIBUTOR in the event of his/her death. It also implies that the DISTRIBUTOR shall be responsible for all the actions carried out by his/her designated Co-Distributor, as well as for compliance with the rights arising from the Co-distributorship. <br>
									TWENTY-FIRST.-.- The DISTRIBUTOR agrees to maintain confidentiality of all the economic, financial, accounting, strategic, marketing, customer, and any
									other information that may be obtained from OMNILIFE pursuant to the present agreement. Likewise, the sales information obtained by the DISTRIBUTOR as
									a result of the relationship originating from this agreement regarding the company’s business, marketing, sales, and promotion practices, are new to the DISTRIBUTOR and have been especially designed by OMNILIFE at a high cost, granting competitive advantages to the company. Because of this, the
									DISTRIBUTOR must observe the strictest confidentiality; he or she may not
									use this private information for any other purposes that those described herein, and is responsible for any damages caused to OMNILIFE due to a breach of
									confidentiality. <br>
									TWENTY-SECOND.- .- In order to ensure that activities performed by the DISTRIBUTOR do not provide unlawful organizations with an opportunity to
									conceal the proceeds of illegal activities, or use resources destined for illegal
									organizations or activities, the DISTRIBUTOR shall put into practice the measures required by law, performing each of his/her operations in accordance
									with the strictest ethical principles and in strict observance of the applicable laws, rules and regulations, especially those related to the prevention of illegal activities or any similar or related activity.TWENTY-THIRD.- .- By entering into
									the present agreement, the DISTRIBUTOR expressly and freely authorizes OMNILIFE to handle the personal information contained in this document in
									accordance with OMNILIFE’S Privacy Policy, which has been made available and can be viewed at www.omnilife.com. In addition, the DISTRIBUTOR may
									exercise his/her right to access, rectify, cancel, or oppose the information, as well as revoke his/her consent to the treatment of said personal information by sending his/her request under the provisions of the Privacy Policy through the email address privacy@omnilife.com, where it will be suitably addressed in a timely manner. <br>
									TWENTY-FOURTH.-.- The DISTRIBUTOR is aware and agrees to his/her personal information being processed by OMNILIFE in its database, to be used
									within the context of the business relationship that exists between the PARTIES, as well as for marketing purposes, including offering products and
									services other than those initially stipulated. Likewise, the DISTRIBUTOR authorizes the company to communicate or transfer this information to other
									companies within the OMNILIFE GROUP on a national and international level. <br>
									TWENTY-FIFTH.- Due to the nature of the business structure and as previously noted, the DISTRIBUTOR may also have access to the information of his/her
									personally sponsored distributors regarding their contact information, product purchases, and of those distributors’ personally sponsored distributors which
									you authorize by signing this contract; the personally sponsored distributors may also have access to their sponsor ́s information, product purchases and other personally sponsored distributors. The Distributor agrees to comply with
									the all applicable laws referring to privacy and data protection; therefore, In the
									event of a breach on behalf of the DISTRIBUTOR, he or she will assume complete responsibility, freeing OMNILIFE from any liability. <br>
									TWENTY-SIXTH.- Any notification or announcement between the PARTIES shall be made to the address that is registered in OMNILIFE’S system at the time of the notification. <br>
									TWENTY-SEVENTH.- <br>
									This agreement shall be governed by and construed in accordance with the laws of the State of Delaware. Any controversy or claim arising out of or relating
									to this agreement, or the breach thereof, shall be settled by arbitration administered by the American Arbitration Association in accordance with its Commer-
									cial Arbitration Rules and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof. Claims shall be heard	by a single arbitrator. The place of arbitration shall be New York, New York. The
									arbitration shall be governed by the laws of the State of Delaware. Except as may be required by law, neither the DISTRIBUTOR nor an arbitrator may
									disclose the existence, content, or results of any arbitration hereunder without the prior written consent of OMNILIFE. <br>
									TWENTY-EIGHT.- For matters not provided for in the present agreement, the PARTIES are subject to the Distributor’s Manual, which as an annex to this
									document represents an integral part of the agreement, and secondly to the applicable rules and regulations. <br>
									TWENTY-NINTHIn the event that any of the terms or provisions of this agreement were to be declared null and void by the competent authority, the rest shall
									remain valid and in effect and the relationship between the PARTIES shall continue pursuant to the terms agreed upon by means of the present document. <br>
								</p>
							</div>
						</div>
						<p class="sansserif">I HEREBY DECLARE THAT OMNILIFE’S PRIVACY NOTICE WAS MADE AVAILABLE TO ME AND AUTHORIZE THE TREATMENT OF MY PERSONAL
						INFORMATION ACCORDING TO THE TERMS AND CONDITIONS AND FOR THE PURPOSES DESCRIBED IN SAID NOTICE.
						</p>
						@elseif (session()->get('lang_id')->short_name == "ESP")
						<div class="row">
							<div class="col">
								<p class="sansserif">
									Una vez leído y comprendido el manual del distribuidor, manifiesto mi interés para
									ser Distribuidor Mercantil Independiente de OMNILIFE y de SEYTÚ COSMÉTICA de ESTADOS UNIDOS DE AMERICA, al amparo del siguiente contrato: <br>
									CONTRATO DE DISTRIBUCION MERCANTIL INDEPENDIENTE QUE CELEBRAN OMNILIFE USA INC, A QUIEN EN LO SUCESIVO SE LE DENOMINARA “OMNILIFE” Y POR LA OTRA PARTE EL PRESENTADO INTERESADO, A QUIEN EN LO SUCESIVO
									Y A PARTIR DE ESTE MOMENTO SE LE DENOMINARÁ EL “DISTRIBUIDOR”, QUIENES DE FORMA CONJUNTA SERÁN DENOMINADOS COMO LAS “PARTES”, QUIENES MANIFIESTAN ESTAR DE ACUERDO EN SUJETARSE A LAS SIGUIENTES
									DECLARACIONES Y CLAUSULAS: <br>
									DECLARACIONES <br>
									I. Declara OMNILIFE: <br>
									a) Que es una empresa legalmente establecida que cumple con la normativa
									aplicable. <br>
									b) Que se dedica, entre otras actividades a la comercialización de diversos productos
									que, en lo sucesivo se les denominará “Productos”. <br>
									c) Que cuenta con las autorizaciones y registros necesarios para desarrollar su
									actividad. <br>
									d) Que por ser una empresa de venta directa de tipo multinivel apegada a la Ley, está
									interesada en que el DISTRIBUIDOR comercialice sus Productos sin exclusividad
									alguna. <br>
									e) Que tiene su domicilio en Legacy Town Center II, 6900 North Dallas Parkway,
									Suite 870, Plano, Texas, 75024. <br>
									II. Declara el DISTRIBUIDOR: <br>
									a) Que realiza actividades comerciales, tiene la capacidad y cuenta con los medios,
									la experiencia y conocimientos necesarios para el desarrollo de dicha actividad. <br>
									b) Que está interesado en ser Distribuidor Mercantil Independiente de OMNILIFE. <br>
									c) Que realiza sus actividades comerciales en forma independiente, no subordinada,
									no exclusiva, sin perjuicio de otras actividades que realiza hoy en día y que seguirá
									realizando. <br>
									d) Que se encuentra inscrito como comerciante ante la autoridad correspondiente,
									para emitir los comprobantes necesarios. <br>
									e) Que ha recibido a su entera satisfacción el Manual del Distribuidor el cual forma
									parte integrante del presente contrato y a su vez declara conocer su contenido y
									entenderlo en su totalidad, estando de acuerdo en respetar sus estipulaciones. <br>
									f) Que su domicilio es el indicado en el formato de presentación previo, al igual que
									el resto de los datos de contacto ahí expuestos. <br>
									Expuesto lo anterior, las partes se sujetan a las siguientes: <br>
									CLAUSULAS <br>
									PRIMERA.- EL DISTRIBUIDOR podrá distribuir los Productos dentro de los Estados
									Unidos de América y en aquellos países donde Omnilife tenga presencia, siempre
									que los productos a distribuir sean adquiridos en el país donde se realizará la reventa
									y que el DISTRIBUIDOR cuente con las autorizaciones necesarias para hacerlo,
									conforme a la legislación del lugar. <br>
									En su condición de DISTRIBUIDOR podrá tener los siguientes beneficios: I) Derecho
									a ciertos niveles de descuento como resultado del volumen de compras personales
									que realice, II) Ganancias por el diferencial que exista entre el precio con descuento
									al que los adquirió y el precio al que realice su reventa; y III) Ganancias por las
									compras de los distribuidores por él presentados y por tanto considerados para
									efectos del presente contrato como incorporados a su red de distribución. Beneficios
									de conformidad con lo señalado en el Manual del Empresario o Distribuidor, que
									como anexo forma parte del presente contrato.
								</p>
							</div>
							<div class="col">
								<p class="sansserif">
									SEGUNDA.- Debido al esquema de multinivel y de pago de ganancias, el DISTRIBUIDOR podrá bajo el mismo esquema y en cualquier país donde OMNILIFE tenga presencia,
									comprar Productos, revenderlos y presentar interesados en distribuirlos, recibiendo
									las ganancias que así le correspondan. El pago de las mismas se canalizará a través de
									OMNILIFE, por lo cual el DISTRIBUIDOR otorga mandato gratuito sin representación
									a OMNILIFE, con el fin de que ésta efectúe la entrega de sus ganancias originadas
									en el exterior por cuenta de OMNILIFE pero a nombre del DISTRIBUIDOR, quien
									además cumplirá con las obligaciones de naturaleza tributaria que recaigan sobre
									el DISTRIBUIDOR. <br>
									TERCERA.- En caso de que EL DISTRIBUIDOR no cuente con las inscripciones,
									registros, comprobantes y autorizaciones fiscales necesarias que las autoridades
									locales pudieran exigir para la actividad comercial aquí pactada, al momento en
									que tenga derecho a recibir una ganancia, OMNILIFE no podrá realizar el pago de
									la misma, hasta en tanto no regularice dicha situación. No obstante, OMNILIFE
									quedará facultada para que a su discreción y voluntad, establezca la forma en que
									podrá diferirlas al DISTRIBUIDOR, previo descuento de todos los gastos e impuestos
									y demás contribuciones que por lo anterior se generen, pudiéndolo hacer como una
									acreditación en el sistema de sus compras directas, conforme a lo previsto en el
									Manual del Distribuidor, o bien de otra forma que así considere. <br>
									CUARTA.- OMNILIFE se compromete a vender al DISTRIBUIDOR los Productos que éste
									requiera, siempre y cuando OMNILIFE los tenga en existencia en sus almacenes. Los
									que siempre serán entregados al DISTRIBUIDOR en perfecto estado de conservación
									cumpliendo las normas sanitarias vigentes. <br>
									QUINTA.- El DISTRIBUIDOR deberá liquidar totalmente el importe de sus compras al
									momento de realizar su pedido, pudiéndolo hacer en cualquiera de las formas de
									pago que en su momento tenga disponibles OMNILIFE. <br>
									SEXTA.- Los precios de los Productos serán fijados por OMNILIFE de acuerdo a su lista
									de precios vigente a la fecha de compra de los mismos por parte del DISTRIBUIDOR.
									OMNILIFE podrá sugerir al DISTRIBUIDOR el precio de reventa al público de los
									Productos adquiridos para tal fin. <br>
									SÉPTIMA.- Los riesgos sobre el cuidado y pérdida de los Productos correrán a cargo
									de su propietario, es decir de OMNILIFE hasta que los entregue al DISTRIBUIDOR
									por virtud de la venta, y del DISTRIBUIDOR a partir de que los reciba por virtud de
									la compra. <br>
									OCTAVA.- En virtud que el DISTRIBUIDOR realiza un negocio propio, así como con
									medios comerciales y personales, podrá manejar sus propias estrategias de venta y
									distribución, sin embargo OMNILIFE le podrá sugerir planes de mercadotecnia que
									pudiera aplicar a los Productos. <br>
									NOVENA.- Todos los gastos que el DISTRIBUIDOR genere por la distribución de
									los Productos tales como pagos de impuestos, gastos de transporte, papelería y
									cualquier otro, serán su responsabilidad. <br>
									DÉCIMA.- En relación con todos los costos y gastos asociados al manejo y entrega, así
									como a la gestión permanente de publicidad y mercadeo de los Productos objeto del
									sistema de distribución multinivel de OMNILIFE, las partes acuerdan que OMNILIFE
									podrá establecer cuotas, que una vez definidas, al igual que el pago de precio,
									estarán a cargo del DISTRIBUIDOR. <br>
									DÉCIMA PRIMERA.- Si el DISTRIBUIDOR al promover la venta de los Productos entre
									sus clientes encuentra que alguno de ellos se interesa también en distribuirlos, podrá
								</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<p class="sansserif">
									presentarlos a OMNILIFE para que soliciten ser distribuidores y suscriban el contrato
									de distribución respectivo, sin que lo anterior genere pago alguno de OMNILIFE hacia el DISTRIBUIDOR por este acto. En caso de formalizarse la distribución, pasará	a formar parte de su red de distribución. <br>
									DÉCIMA SEGUNDA.- Los derechos y obligaciones del DISTRIBUIDOR respecto del
									presente contrato no podrán ser cedidos sin el consentimiento expreso, previo y por
									escrito de OMNILIFE. <br>
									DÉCIMA TERCERA.- El DISTRIBUIDOR se conducirá con toda honestidad y no realizará
									prácticas comerciales engañosas ni contrarias a la ética, por lo tanto será obligación
									del DISTRIBUIDOR cumplir en todo momento con las leyes que puedan resultarle
									aplicables en virtud de su negocio. <br>
									DÉCIMA CUARTA.- EL DISTRIBUIDOR deberá respetar todos los derechos de
									propiedad intelectual y derechos de autor de las empresas del GRUPO OMNILIFE y de
									sus filiales. EL DISTRIBUIDOR no podrá utilizar el nombre comercial de cualquiera de
									las empresas del GRUPO OMNILIFE, marcas registradas o cualquier signo distintivo
									de su titularidad, bajo las cuales se presentan comercialmente los Productos, en
									ningún medio de publicidad, medios electrónicos, tarjetas de presentación, carteles,
									folletos, vehículos, chequera o papelería, sin el previo consentimiento por escrito de
									OMNILIFE. <br>
									DÉCIMA QUINTA.- EL DISTRIBUIDOR por ningún motivo podrá presentarse como
									empleado o atribuirse facultades de representación de OMNILIFE, por lo que queda
									excluida la posibilidad de considerar al DISTRIBUIDOR como apoderado, mandatario
									o comisionista de OMNILIFE. En consecuencia, ninguna de las partes tendrá
									obligación alguna por cuenta y nombre de la otra, ni como representante o agente de
									la otra. Por lo que en caso de que el DISTRIBUIDOR se adjudicara dicha condición será
									responsable de los daños o perjuicios ocasionados a OMNILIFE o a cualquier tercero. <br>
									DÉCIMA SEXTA.- El presente contrato tendrá una duración indefinida siempre que se
									cumpla con lo establecido en el mismo y en el Manual del Distribuidor. Sin embargo,
									cualquiera de las partes podrá dar por terminado en forma unilateral el presente
									contrato en cualquier tiempo y sin causa alguna, mediante aviso por escrito dado
									con 30 días calendario de anticipación, sin responsabilidad para la parte que haya
									solicitado la terminación. Transcurrido el plazo correspondiente el contrato queda
									resuelto de pleno derecho. Con la terminación del presente contrato, ninguna de
									las partes tendrá derecho posterior alguno a excepción de la liquidación de adeudos
									pendientes. <br>
									DÉCIMA SEPTIMA.- Si el DISTRIBUIDOR decide dar de baja su Contrato de Distribución,
									sin importar la razón y por el solo hecho que así lo solicite, OMNILIFE, en virtud de su
									condición de proveedor se compromete a la recompra de los productos que hubieras
									comprado durante los 12 meses anteriores a la fecha de cancelación de tu Contrato.
									El precio de recompra establecido será el 90% del precio neto de compra de cada
									producto. <br>
									DÉCIMA OCTAVA.- En caso de incumplimiento por parte del DISTRIBUIDOR a cualquiera
									de sus obligaciones emanadas del presente Contrato o del Manual del Distribuidor,
									OMNILIFE podrá dar por terminado el mismo, quedando automáticamente resuelto
									una vez que el DISTRIBUIDOR reciba de OMNILIFE una comunicación escrita
									en el sentido de hacer valer esta cláusula, sin perjuicio de las acciones legales
									correspondientes que OMNILIFE pueda hacer valer en contra del DISTRIBUIDOR,
									derecho que en los mismos términos y de forma recíproca tendrá el DISTRIBUIDOR.
									Con la terminación del presente contrato, ninguna de las partes tendrá derecho
									posterior alguno a excepción de la liquidación de adeudos pendientes. <br>
									DÉCIMA NOVENA.- En virtud del tipo de negocio, el DISTRIBUIDOR acepta que
									OMNILIFE tiene el derecho de modificar en cualquier momento el Manual del
									Distribuidor, mismo que ha puesto a disposición del DISTRIBUIDOR también de manera
									electrónica para tener acceso al mismo. Las modificaciones estarán a disposición del
									DISTRIBUIDOR en los paneles informativos de cada Centro de Distribución y en la
									página Web de OMNILIFE, a la cual sabe ingresar el DISTRIBUIDOR, mismas que se
									publicaran previo a su entrada en vigor. En caso de que el DISTRIBUIDOR no esté de
									acuerdo con alguna modificación, tendrá derecho a dar por terminado este contrato,
									mediante simple aviso notificado a OMNILIFE, y de no haber pronunciamiento
									en contra por parte del DISTRIBUIDOR en el plazo señalado, las modificaciones
									al Manual del Distribuidor Mercantil Independiente se entenderán aprobadas y
									aceptadas, comenzando a surtir efectos. <br>
									VIGESIMA.- El DISTRIBUIDOR no se encuentra obligado a comprar determinados
									Productos, ni con determinada frecuencia, así como tampoco estará sujeto a horario
									alguno para la distribución de los mismos, ni estará subordinado a instrucciones u
									órdenes del personal dependiente de OMNILIFE, ni deberá rendir cuentas de sus
									actividades a los mismos, excepto de aquéllas que se requieran por la naturaleza del
									presente contrato. <br>
									VIGESIMA-PRIMERA.- EL DISTRIBUIDOR podrá autorizar a una persona para que
									pueda participar en la distribución de los productos OMNILIFE, bajo este mismo
									contrato utilizando la figura de Coempresario, quien participará en forma directa en
									su negocio por medio de la compra – reventa de Productos, así como en la operación
									y comercialización de su negocio independiente.
								</p>
							</div>
							<div class="col">
								<p class="sansserif">
									La designación de Coempresario que en su caso realice el DISTRIBUIDOR, implica que
									este quede como beneficiario de todos los derechos y obligaciones del contrato de
									distribución en caso de muerte del DISTRIBUIDOR.
									También implica que el DISTRIBUIDOR sea responsable de todos los actos del
									Coempresario su caso designado, así como del respeto a todos los derechos
									emanados del tipo de relación que entre estos exista. <br>
									VIGÉSIMA- SEGUNDA.- EL DISTRIBUIDOR se obliga a guardar reserva de toda la
									información económica financiera, contable, estratégica, de mercado, cartera de
									clientes, o de otra índole, que en la ejecución del presente contrato pueda obtener
									de OMNILIFE. Así mismo, la información comercial que ha conocido y conocerá el
									DISTRIBUIDOR derivado de la relación pactada en este contrato, relacionada con la
									forma de hacer negocios, de comercializar, de revender y de promocionar, son nuevas
									para el DISTRIBUIDOR y han sido diseñadas especialmente por OMNILIFE, teniendo
									altos costos y representando ventajas competitivas para ésta, razón por la que el
									DISTRIBUIDOR deberá de observar la más estricta confidencialidad al respecto, no
									pudiendo emplear la información confidencial obtenida, para fines distintos al aquí
									señalado, siendo responsable en su caso, por los daños y perjuicios ocasionados a
									OMNILIFE. <br>
									VIGÉSIMA-TERCERA.- Con el fin de garantizar que las operaciones realizadas por el
									DISTRIBUIDOR no se presten para que organizaciones fuera de la ley encubran el
									producto de actividades ilícitas, ni utilicen recursos con destino a la comisión de
									ilícitos, pondrá en práctica las medidas exigidas por la ley, realizando cada una de sus
									operaciones bajo los más estrictos principios éticos y en observancia de las leyes y
									normas relativas; en especial aquéllos relacionados con la prevención de actividades
									ilícitas o cualquier similar, derivada o relacionada. <br>
									VIGÉSIMA-CUARTA.- El DISTRIBUIDOR a través de la celebración del presente contrato
									autoriza de manera libre y expresa a OMNILIFE para que realice el tratamiento de
									los datos personales consignados en el presente documento conforme a la Política
									de Privacidad de OMNILIFE, misma que ha sido puesta a su disposición y puede
									ser consultada en www.omnilife.com; asimismo, el DISTRIBUIDOR podrá ejercer
									cualquiera de los derechos de acceso, rectificación, cancelación u oposición, así
									como revocar su consentimiento para el tratamiento de dichos datos personales
									enviando su solicitud conforme a lo establecido en la Política de Privacidad al correo
									electrónico privacidad@omnilife.com donde se le atenderá en tiempo y forma. <br>
									VIGÉSIMA-QUINTA.- El DISTRIBUIDOR conoce y está de acuerdo en que sus datos
									personales sean tratados por OMNILIFE en su base de datos, para ser utilizados en el
									marco de la relación comercial que existe entre las PARTES, así como para el desarrollo
									de acciones comerciales, incluyendo el ofrecimiento de productos y servicios al
									margen de los inicialmente estipulados. De la misma forma, el DISTRIBUIDOR
									autoriza la comunicación por transferencia de los datos a otras empresas del GRUPO
									OMNILIFE a nivel nacional e internacional. <br>
									VIGÉSIMA-SEXTA.- Debido al esquema de negocio, el presentador, pudiera tener
									acceso a datos de contacto del DISTRIBUIDOR, de sus compras de Productos y
									de sus presentados lo cual usted autoriza con la firma del presente contrato;
									asimismo el DISTRIBUIDOR pudiera tener acceso también a datos de contacto de
									sus presentados, de sus compras de Productos y a su vez de los presentados de
									éstos, por lo que se compromete a cumplir lo dispuesto en la Ley en materia de
									protección de datos y privacidad, por lo que en el supuesto de incumplimiento por
									parte del DISTRIBUIDOR, éste asumirá la total responsabilidad, liberando a OMNILIFE
									de responsabilidad alguna. <br>
									VIGÉSIMA-SEPTIMA.- Cualquier notificación, aviso o emplazamiento que se deban
									efectuar las PARTES, se deberá llevar a cabo en el domicilio que se tenga registrado
									en el sistema de OMNILIFE al momento de la notificación. <br>
									VIGÉSIMA-OCTAVA.- El presente contrato se regirá e interpretara por las leyes
									del Estado de Delaware. Cualquier controversia o reclamación que surja de este
									contrato o el incumplimiento del mismo, beberá ser resuelto por medio del arbitraje
									administrado por la Asociación Americana de Arbitraje de conformidad con su
									Reglamento de Arbitraje Comercial y sobre el laudo dictado por el árbitro podrá
									ser presentado en cualquier tribunal que tenga jurisdicción sobre el mismo, las
									reclamaciones serán atendidas por un solo arbitro. El lugar de arbitraje será Nueva
									York, Nueva York y el arbitraje se regirá por las leyes del Estado de Delaware. Salvo
									que lo exija la ley, ni el DISTRIBUIDOR ni un árbitro podrán revelar la existencia,
									contenido, o resultado de cualquier arbitraje en virtud del presente, sin el
									consentimiento previo por escrito de Omnilife.
									VIGÉSIMA-OCTAVA.- Para lo no previsto en el presente contrato, las partes se sujetan
									al Manual del Distribuidor, que como anexo forma parte integral de este contrato, y
									en segundo término a las normas aplicables correspondientes. <br>
									VIGÉSIMA-NOVENA.- Para el caso de que alguna de las cláusulas o disposiciones de
									este contrato llegaran a ser declaradas nulas por la autoridad competente, quedarán
									vigentes y a salvo todas las demás, persistiendo la relación entre las partes, en los
									términos en que mediante este documento, las mismas quisieron obligarse.
								</p>
							</div>
						</div>
						<p class="sansserif">DECLARO QUE EL AVISO DE PRIVACIDAD DE OMNILIFE FUE PUESTO A MI DISPOSICIÓN Y ESTOY DE ACUERDO EN QUE
						MIS DATOS PERSONALES SE TRATEN CONFORME A LAS FINALIDADES Y CONDICIONES DESCRITAS EN EL MISMO.</p>
						<p>Al aceptar, expresamente reconoce haber leído y entendido el Contrato de Distribución Independiente y el Manual del Distribuidor, estando de acuerdo en el contenido de cada una de sus cláusulas y disposiciones. De igual forma, reconoce y acepta los cambios que pudieran generarse en los mismos por la dinámica del negocio Multinivel.</p>
						@endif
					</div>
				</div>
		    </div>
		    <div id="m-btn" class="modal-footer">
		      <button id="m-cancel" type="button" class="border-button menu-button btn btn-secondary btn-lg btn-block" data-dismiss="modal">{{trans('welcome.register.dont_agree')}}</button>
		      <button id="m-print" onclick='printDiv();' type="button" class="border-button menu-button btn btn-secondary btn-lg btn-block separate">{{trans('welcome.register.print')}}</button>
		      <button id="m-accept" type="button" class="border-button menu-button btn btn-secondary btn-lg btn-block" data-dismiss="modal">{{trans('welcome.register.agree')}}</button>
		    </div>
	  	</div>  
	</div>
</div>