<?php

return [

    'title' => 'Terms and Conditions',
    'part1' => '<p class="text-justify stylesh-font15">Thanks for visiting https://www.omnilife.com/. This website (<b class="products-colorGreen ">Nfuerza</b>) is a service provided by the Omnilife Group, S.A. of C.V. and its subsidiaries ("Omnilife") to facilitate the purchase of and access to Omnilife\'s products, programs and services. All content, information and services provided on the Site and through it may be used only in accordance with the following terms and conditions (the "Terms of Use").</p>
        <p class="text-justify stylesh-font15">USING THIS SITE CONSTITUTES THE USER’S ACCEPTANCE TO BE BOUND BY THE FOLLOWING TERMS OF USE, WITH POSSIBLE MODIFICATIONS MADE OCCASIONALLY BY OMNILIFE. READ THEM CAREFULLY BEFORE USING THE SITE. IF YOU DO NOT AGREE WITH ANY PORTION OF THESE TERMS OF USE, YOU SHOULD REFRAIN FROM USING THE SITE.</p>',
    'part2' => '<p class="text-justify stylesh-font15"><b>User license </b></p>
        <p class="text-justify stylesh-font15">You are granted a limited, non-exclusive and non-transferable license to access the Site and its content in accordance with these Terms of Use. If you are under 18, you may only use the Site with the participation of a parent or guardian. The Site is hosted in Mexico, but contains general information that is suitable for access and global use. Omnilife makes no representation that all materials on the Site are suitable or available for use outside of Mexico, and access to these materials from territories where their content is illegal is prohibited. The Site may contain references or cross-references to products, programs or services that have not been publicized or that are not available in your country, and such references do not imply that Omnilife has planned to advertise or make available such products, programs or services in its country. Consult your local Omnilife contact to obtain information related to the products, programs and services available to you or, if you access this Site from other places, you may choose to follow the link to an affiliated website where you will find information related to availability, claims and comparisons of products, programs and services corresponding to where you are located (See Links to affiliated websites, below). Those who access this Site from other places do so on their own initiative and are responsible for complying with local laws, which include the laws related to the transmission of technical data exported from Mexico or the territory in which they reside.</p>
        <p class="text-justify stylesh-font15">Omnilife reserves the right to refuse the service at its absolute discretion and without prior notice. You are solely responsible for your use of the Site and agree to compensate, exonerate and defend Omnilife from all claims, damages, losses, liabilities, costs and expenses, including attorneys\' fees, resulting from your use or misuse of the Site. The publication or transmission of illegal, threatening, libelous, defamatory, obscene, indecent, incendiary, pornographic or profane material, or of any material that could constitute or encourage conduct that could be considered a criminal offense, give rise to civil liability is strictly prohibited. or otherwise violate any law.</p>',
    'part3' => '<p class="text-justify stylesh-font15"><b>Limitations on its use</b></p>
        <p class="text-justify stylesh-font15">No material on the Omnilife Site may be used, copied, reproduced, republished, downloaded, published, displayed, transmitted or distributed in any way, without the prior written authorization of Omnilife, except that you may download a copy of the materials in a only computer only for your personal, non-commercial and private use, as long as (i) you keep intact all intellectual property notices and other privacy notices, and (ii) you do not make any changes to the materials. It is not allowed, without the prior written permission of Omnilife, to frame or replicate any material contained on this Site on any other server. The unauthorized use of such material in any other computer environment or website is expressly prohibited.</p>',
    'part4' => '<p class="text-justify stylesh-font15"><b>Privacy and personal information</b></p>
        <p class="text-justify stylesh-font15">Your use of the Site is also subject to the terms of the Privacy Policy. You acknowledge that you have read and understand the Privacy Policy, and accept the use of all personal information that you provide in accordance with the terms of the Privacy Policy and for the purposes set forth herein.</p>',
    'part5' => '<p class="text-justify stylesh-font15"><b>Intellectual Property Rights</b></p>
        <p class="text-justify stylesh-font15">Copyright: design, source code, programming, navigation structure, databases, text, content, selection and arrangement of elements, organization, graphics, photographs, images, compilation, magnetic translation, digital conversion and all other elements contained on the Site and matters related to the Site (collectively, the "Elements") are protected by copyright laws and treaties. corresponding international The publication of any of these Elements on the Site does not constitute a waiver of any right in these Elements, and does not confer any license or transfer of rights of any kind in relation to these. Unless otherwise stated in this document, no Element may be used, copied, reproduced, downloaded, published, displayed, transmitted, modified or distributed in any form or by any means, including, electronic means, mechanical means. , photocopy, recording or other, without the prior written permission of Omnilife.</p>
        <p class="text-justify stylesh-font15">Trademark: Omnilife®, the logo, and all product names, company names and other trademarks and logos included in the Site, unless otherwise specified, are trademarks or commercial images of Omnilife (in the form collectively, the "Trademarks") and are protected by the corresponding international laws and treaties. All other product names, trademarks, company names, logos, service marks or commercial images mentioned, displayed, cited or otherwise indicated on the Site are the property of their respective owners. The publication of the Marks on the Site does not constitute a waiver of any right in such Marks, and does not confer any license or transfer of rights of any kind in relation to them.</p>
        <p class="text-justify stylesh-font15">The Elements and Marks are mentioned in this document as the "material" or the "materials".</p>
        <p class="text-justify stylesh-font15">The use and / or misuse of any or all of the Elements, Brands and / or any other material contained on the Site is expressly prohibited, without the prior written permission of its owner.</p>',
    'part6' => '<p class="text-justify stylesh-font15"><b>Guarantee exemption</b></p>
        <p class="text-justify stylesh-font15">THE OMNILIFE SITE AND ITS CONTENTS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, OMNILIFE EXPRESSLY DISCLAIMS ANY WARRANTY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, AND WARRANTIES ARISING BY STATUTE OR OTHERWISE. BY LAW OR BY THE COURSE OF TRANSACTIONS OR COMMERCIAL USE. OMNILIFE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WITH RESPECT TO COMPLETENESS, ACCURACY, CORRECTNESS, COMPLETENESS, RELIABILITY, CURRENTNESS, SUITABILITY, SUITABILITY, FUNCTIONALITY, AVAILABILITY, OR PERFORMANCE OF THIS SITE OR CONTENT. OR THE SERVICES PROVIDED ON THE SITE OR ACCESSIBLE THROUGH THEM. OMNILIFE DOES NOT WARRANT THAT THE OPERATION OF THIS SITE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT THIS SITE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS FOR THE EQUIPMENT OR THE SOFTWARE.</p>',
    'part7' => '<p class="text-justify stylesh-font15"><b>Limitation of liability</b></p>
        <p class="text-justify stylesh-font15">IN NO EVENT WILL OMNILIFE MAKE ANY REPRESENTATIONS OR ASSUME RESPONSIBILITY FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING FROM THE USE OR INABILITY TO USE THIS SITE (OR THE CONTENT OR SERVICES PROVIDED ON THE SITE OR ACCESSIBLE TO THE SITE). THROUGH THIS) OR IN CONNECTION WITH THIS, OR OTHERWISE, EVEN IF OMNILIFE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>',
    'part8' => '<p class="text-justify stylesh-font15"><b>Errors and corrections</b></p>
        <p class="text-justify stylesh-font15">While Omnilife makes reasonable efforts to include accurate and up-to-date information on the Site, Omnilife does not guarantee or declare that the Site will be free of errors. Errors in data entry and other technical problems can sometimes cause inaccurate information to be displayed. Omnilife reserves the right to correct any inaccuracies or typographical errors on the Site, and will not be responsible for such errors. Omnilife may also make improvements and / or changes in the applications, functionality or content of the Site at any time. If you notice any information or description that you consider incorrect, please contact us as described in the "Contact" section, and Omnilife will verify it for you.</p>',
    'part9'=> '<p class="text-justify stylesh-font15"><b>Links to affiliate websites</b></p>
        <p class="text-justify stylesh-font15">The Omnilife Site contains links to affiliated websites, which allow you to receive specific information regarding the availability, claims and product comparisons for the place where you live. Affiliates are responsible for their own websites complying with the laws in force in their respective jurisdictions, and undertake to review them. These links are provided only to offer you greater convenience. Omnilife does not approve or accept any responsibility for the content of an affiliated website or for the accessibility of the resources available in them. Omnilife suggests that you carefully review the terms of use of each affiliated website that you choose to access from the Site.</p>',
    'part10'=> '<p class="text-justify stylesh-font15"><b>Presentations</b></p>
        <p class="text-justify stylesh-font15">Omnilife is pleased to listen to the users of the Site and appreciates your comments regarding the content and services. Any information that is not personally identifiable, which is addressed in the Site\'s Privacy Policy, any suggestions, ideas, concepts, material or other information that you submit to this Site or through it ("Presentations") will become permanently owned by Omnilife. Omnilife will have no obligation of any kind with respect to said Presentations and will be free to use and disclose the Presentations to others without limitation.</p>',
    'part11'=> '<p class="text-justify stylesh-font15"><b>Legislation and jurisdiction in force</b></p>
        <p class="text-justify stylesh-font15">These Terms of Use are governed by the laws of Mexico and are interpreted in accordance with these laws, without giving effect to any principle of conflicts of laws. Any dispute or dispute arising out of your use of the Site should be sent to the personal jurisdiction of any state or federal court located in Mexico, which you irrevocably accept. If it is determined that any provision of these Terms of Use is illegal, void or for any unenforceable reason, that provision will be deleted and will not affect the validity and enforceability of the remaining provisions.</p>',
    'part12'=> '<p class="text-justify stylesh-font15"><b>Changes to the Site and Terms of Use</b></p>
        <p class="text-justify stylesh-font15">Omnilife reserves the right, at its absolute discretion, to change the Site and / or its content and these Terms of Use at any time, without prior notice. The updated versions of the Terms of Use will be published on the Site and will be effective immediately. The date of the latest version is indicated below. Check it frequently, especially before using the Site, to see if these Terms of Use have changed. Your continued use of the Site after any change in the Terms of Use constitutes your consent to such changes.</p>',

];