INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (1, '001501236AAV', 'AGUILAR ALVAREZ VIVIANA', 'kimitzeliii78@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (2, '001509360ALS', 'GARCIA AGUILAR KIMBERLEY IZETT', 'kimberlygarciaomnilife@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (3, '001422079CA', 'CORTES ALVARO', 'alvaro93458@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (4, '314581LLJ', 'LEPE LOPEZ JOSE CARMEN', 'pepelepe51@hotmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (5, '001219691HGC', 'HUERTA GONZALEZ CARLOS ALBERTO', 'christinaavila74@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (6, '001022019GCR', 'GONZALEZ CERRILLO ROSA', 'rosag@grupolosangelinos.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (7, '1811428CGV', 'CUEVAS GONZALEZ VIOLETA', 'violetacuevas64@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (8, '001500102DG', 'GALLARDO DEMETRIO', 'creo@omnilife.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (9, '57741750BMF', 'BARRETO MORA FANNY TATIANA', 'tatianamolinaomnilifeca@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (10, '001529578SVR', 'SOBERANES  VIDAL  RAZIEL', 'picaa2011@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (11, '798649SSD', 'SOSA SILVA DOMINGO MANUEL', 'dsosausa@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (12, '001021838SC', 'VALDEZ CATALINA', 'catalinacvr@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (13, '001376053GF', 'GALLEGOS FRANCO', 'franky2797@gmail.com', 1);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (14, '001182689MJ', 'MONTES JULIA', 'montesjulia18066@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (15, '001469099CE', 'CISNEROS ESTHER', 'ester.angelisima56@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (16, '001538742SF', 'SALGADO FRANCISCO', 'francisc_salgado@sbcglobal.net', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (17, '680299MRP', 'MARTINON PEDRO', 'losmorados@icloud.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (18, '1570864EVH', 'ESPINOZA VEGA HILDA GEORGINA', 'hildaespinoza54@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (19, '001432098JS', 'JIMENEZ SILVIA JEANNETTE', 'silviajimenez0575@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (20, '001358810FL', 'FLORES LUCINA', 'luzbonita92@hotmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (21, '001481970EYG', 'GUZMAN ERIKA', 'diamanteusaeyg@yahoo.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (22, '154612PNC', 'PASTEN NADER CARLOS JULIAN', 'usamagnus@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (23, '001449659CAM', 'CERVANTES ARENAS MARIA GUADALUPE', 'mari12emi@hotmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (24, '001516462ACA', 'ACUAHUITL CIELO ANDRES', 'viasupremeinternacional@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (25, '001509955AIC', 'AVILA  INGA  CESAR', 'cesaravilainga24@hotmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (26, '001379269PM', 'PINON MARCOS', 'pinogroup1@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (27, '001099956CO', 'CASTANEDA OFELIA', 'ofelia.omnilife@hotmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (28, '002000116EPA', 'ESPINOSA POZO ADAN', 'aepozo2005@yahoo.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (29, '001100204LG', 'LUCERO GONZALO', 'omnitiempo@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (30, '001004532OJ', 'ORTEGA JOSE MARIA', 'daliciaortega2@att.net', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (31, '001008699RR', 'HERNANDEZ GARCIA ROSA', 'hernandezrosa1262@Gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (32, '001204316BI', 'CONSTANTINO BAZARTE IGNACIA', 'ignaciaconstantino@yahoo.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (33, '001039871MC', 'MURILLO CARMEN A.', 'Carmenmurillo01@Icloud.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (34, '001352072VMG', 'VALENZUELA MARIA GUADALUPE', 'lupeyavomnilife@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (35, '001486791MM', 'MANZO GALINDO GUILLERMO', 'gmgmanzo@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (36, '001481672EP', 'ESPINOZA PEDRO', 'pedro.omnilife57@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (37, '001502700RL', 'RAMOS LESLIE', 'ramosleslie405@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (38, '001541341VM', 'VALENCIA MYRKA', 'myrkavondion@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (39, '001535551GCM', 'GARIBAY CANTU MARTHA', 'marthagaribay1960@hotmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (40, '001313355MM', 'MADRID MARIA GUADALUPE', 'mmadrid1516@yahoo.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (41, '001251160IL', 'IBARRA LORENA', 'lorena-ib@hotmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (42, '001416648LE', 'O* BRIEN III ELIZABETH', 'omnivida18@gmail.com', 0);
INSERT INTO `pool_distributors`(`id`, `eo_number`, `eo_name`, `eo_email`, `used`) VALUES (43, '001392045BRL', 'BARAJAS ROQUE LORENA', 'empresariosomni@yahoo.com', 0);
