INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (1, 1, 'Alabama', 'AL', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (2, 1, 'Alaska', 'AK', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (3, 1, 'Arizona', 'AZ', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (4, 1, 'Arkansas', 'AR', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (5, 1, 'California', 'CA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (6, 1, 'Carolina del Norte', 'NC', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (7, 1, 'Carolina del Sur', 'SC', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (8, 1, 'Colorado', 'CO', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (9, 1, 'Connecticut', 'CT', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (10, 1, 'Dakota del Norte', 'ND', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (11, 1, 'Dakota del Sur', 'SD', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (12, 1, 'Delaware', 'DE', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (13, 1, 'Florida', 'FL', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (14, 1, 'Georgia', 'GA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (15, 1, 'Haw‡i', 'HI', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (16, 1, 'Idaho', 'ID', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (17, 1, 'Illinois', 'IL', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (18, 1, 'Indiana', 'IN', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (19, 1, 'Iowa', 'IA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (20, 1, 'Kansas', 'KS', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (21, 1, 'Kentucky', 'KY', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (22, 1, 'Luisiana', 'LA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (23, 1, 'Maine', 'ME', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (24, 1, 'Maryland', 'MD', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (25, 1, 'Massachusetts', 'MA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (26, 1, 'M’chigan', 'MI', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (27, 1, 'Minnesota', 'MN', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (28, 1, 'Misisipi', 'MS', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (29, 1, 'Misuri', 'MO', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (30, 1, 'Montana', 'MT', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (31, 1, 'Nebraska', 'NE', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (32, 1, 'Nevada', 'NV', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (33, 1, 'Nueva Jersey', 'NJ', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (34, 1, 'Nueva York', 'NY', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (35, 1, 'Nuevo Hampshire', 'NH', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (36, 1, 'Nuevo MŽxico', 'NM', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (37, 1, 'Ohio', 'OH', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (38, 1, 'Oklahoma', 'OK', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (39, 1, 'Oreg—n', 'OR', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (40, 1, 'Pensilvania', 'PA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (41, 1, 'Rhode Island', 'RI', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (42, 1, 'Tennessee', 'TN', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (43, 1, 'Texas', 'TX', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (44, 1, 'Utah', 'UT', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (45, 1, 'Vermont', 'VT', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (46, 1, 'Virginia', 'VA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (47, 1, 'Virginia Occidental', 'WV', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (48, 1, 'Washington', 'WA', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (49, 1, 'Wisconsin', 'WI', '2018-01-11 17:08:21', NULL, NULL, 1);
INSERT INTO `state`(`state_id`, `country_id`, `state`, `state_key`, `created_at`, `updated_at`, `deleted_at`, `estatus`) VALUES (50, 1, 'Wyoming', 'WY', '2018-01-11 17:08:21', NULL, NULL, 1);
