<?php

return [

    'title' => 'Política de Privacidad',
    'part1' => '<p class="text-justify stylesh-font15"><b class="products-colorGreen ">N FUERZA</b> es un sitio más de <b class="products-colorViolet">Grupo Omnilife</b> y como tal, pone a tu disposición el siguiente aviso de privacidad para tu tranquilidad:
        En <b>Omnilife</b> entendemos lo importante de su privacidad. Siendo consecuentes con esta consideración tenemos el compromiso de respetar y proteger la confidencialidad de su información privada y datos personales.
        Omnilife regula el tratamiento de sus datos mediante un equipo internacional, en representación de todas las regiones geográficas en las que tenemos tratos comerciales y procesos de negocio. Es de nuestro especial interés cumplir con las normativas nacionales de cada país donde tenemos presencia, por lo que puede tener la certeza de que su privacidad será nuestra prioridad.
        Grupo Omnilife, S.A. de C.V. (<b>Omnilife</b>), con domicilio en  Av. Inglaterra # 3089  int. I, Col. Vallarta Poniente, C.P. 44110, Guadalajara, Jalisco, México, le comunica que es el responsable del uso y protección de sus datos personales recabados en línea, y al respecto le informamos lo siguiente: *</p>',
    'part2' => '<p class="text-justify stylesh-font15"><b>¿PARA QUÉ FINES UTILIZAREMOS SUS DATOS PERSONALES?</b></p>
        <p class="text-justify stylesh-font15">Para mejorar su experiencia y brindarle una atención de calidad, utilizaremos su información personal para las siguientes finalidades principales, según lo solicite:</p>
        <p class="text-justify stylesh-font15"><b>I.</b>Fines de Identificación. <b>II.</b> A fin de dar cumplimiento a las reglas de negocio. <b>III.</b> Permitir una comunicación eficaz y dar mayor agilidad a sus solicitudes, acceso a centros de distribución y eventos especiales. <b>IV.</b> Procesar sus compras y dar seguimiento a sus pedidos de productos y/o servicios adquiridos. <b>V.</b> Brindarle asesoría y medios para el desarrollo del esquema de negocio. <b>VI.</b> De participación en bonos y/o incentivos <b>VII.</b> En caso de ingresar al plan de ventas y mercado, poder otorgar los respectivos bonos, reembolsos y/o premios. <b>VIII.</b> De participación en campañas, para las cuales se podrán publicar sus fotografías y/o comentarios compartidos (En cada campaña se especificarán las bases de participación y privacidad de su información). <b>IX.</b> Calificar su experiencia como distribuidor. <b>X.</b> Dar seguimiento a sus consultas, quejas y/o sugerencias.</p>
        <p class="text-justify stylesh-font15">A los clientes y distribuidores, les informamos que sus datos podrán ser utilizados adicionalmente para las siguientes finalidades:</p>
        <ul class="stylesh-font15">
            <li>Fines estadísticos.</li>
            <li>Para propósitos de análisis de mercado.</li>
            <li>Fines publicitarios y comerciales, para dar a conocer nuestros productos, servicios, promociones y/o eventos.</li>
        </ul>
        <p class="text-justify stylesh-font15"><b>Imágenes captadas por cámaras de video vigilancia:</b></p>
        <p class="text-justify stylesh-font15">Por motivos de seguridad, en nuestras diversas instalaciones y centros de distribución, contamos con equipo de video vigilancia. Le informamos que las imágenes obtenidas de las mismas, son monitoreadas solo por personal autorizado; esta información permanece en nuestros archivos por un período de 3 meses, posteriormente se procede a su eliminación.</p>
        <p class="text-justify stylesh-font15"><b>Datos recabados vía telefónica:</b></p>
        <p class="text-justify stylesh-font15">Los datos personales recabados a través de nuestros centros de atención telefónica, se regirán bajo los mismos criterios de la presente política. Las grabaciones de audio son resguardadas con estrictos controles de seguridad. Los datos compartidos por vía telefónica son responsabilidad de quien los comunica.</p>
        <p class="text-justify stylesh-font15"><b>Redes sociales:</b></p>
        <p class="text-justify stylesh-font15">Las redes sociales constituyen una herramienta de comunicación entre plataformas digitales de los distintos usuarios y Omnilife, sin embargo, la información proporcionada dentro de redes sociales no constituye parte de los datos personales sujetos a la protección del presente aviso; para conocer dicho tratamiento, favor de verificar la política de privacidad correspondiente al proveedor del servicio.</p>',
    'part3' => '<p class="text-justify stylesh-font15"><b>¿QUÉ DATOS PERSONALES UTILIZAREMOS PARA ESTOS FINES?</b></p>
        <p class="text-justify stylesh-font15">Para llevar a cabo las finalidades antes citadas, utilizaremos las siguientes categorías de datos personales, según sea necesario:</p>
        <ul class="text-justify stylesh-font15">
            <li>	Datos de contacto.</li>
            <li>	Datos de identificación personal.</li>
            <li>	Datos de identificación fiscal/tributaria.</li>
            <li>	Imágenes captadas por cámaras de video vigilancia.</li>
            <li>	Datos bancarios. (Omnilife no registra sus contraseñas bancarias en ninguna base de datos).</li>
        </ul>
        <p class="text-justify stylesh-font15">De ser necesario recabar otros datos de su parte o utilizarlos para otras finalidades distintas a las aquí establecidas, nos pondremos en contacto con usted para obtener su consentimiento. El suministro de los datos personales de menores de edad es facultativo y debe realizarse con autorización de los padres de familia o representantes legales del menor.</p>
        <p class="text-justify stylesh-font15">Los datos personales facilitados se almacenarán en los bancos de datos que forman parte del sistema de información de Omnilife y serán tratados para poder llevar a cabo las finalidades expuestas anteriormente según lo solicitado y autorizado por su parte.</p>
        <p class="text-justify stylesh-font15"><b>Datos de Menores de Edad:</b>
        <p class="text-justify stylesh-font15">El suministro de los datos personales de menores de edad es facultativo y debe realizarse con autorización de los padres de familia o representantes legales del menor.</p>',
    'part4'=> '<p class="text-justify stylesh-font15"><b>¿CON QUIÉN COMPARTIMOS SU INFORMACIÓN PERSONAL Y PARA QUÉ FINES?</b></p>
        <p class="text-justify stylesh-font15">Le informamos que sus datos personales pueden ser compartidos con empresas y asociaciones, controladoras, subsidiarias, filiales y/o afiliadas de Omnilife, esto para dar cumplimiento a los fines antes mencionados. Además de lo anterior, Omnilife podrá compartir algunos o todos sus datos personales con autoridades competentes en los casos legalmente previstos.</p>
        <p class="text-justify stylesh-font15">Al momento de ingresar sus datos en alguno de los distintos formularios en línea, usted autoriza que los mismos sean transferidos al país de México, centro de nuestras operaciones de negocio, donde de ser necesario, se redirigirán a su país de origen para cumplir con las finalidades señaladas. En todo momento, la información será tratada y protegida bajo estrictos procesos de seguridad y privacidad, con alta calidad y confidencialidad; con pleno apego a lo dispuesto por la legislación nacional y estándares internacionales.</p>
        <p class="text-justify stylesh-font15">Le informamos que por nuestro esquema de negocio, cuando usted realice compra de productos, podremos compartir y/o permitir el acceso a información que usted nos haya proporcionado al distribuidor titular del código de referencia que usted haya ingresado al momento de realizar su compra, lo que permitirá a nuestros distribuidores dar seguimiento a sus pedidos y ofrecerle productos y/o servicios que pueden serle de interés (hacemos de su conocimiento que los distribuidores se encuentran bajo obligación contractual para mantener la confidencialidad de su información). En el momento que recabamos su información personal, usted tendrá la opción de aceptar o rechazar la transferencia de su información para dichos propósitos de mercadeo.</p>
        <p class="text-justify stylesh-font15">Omnilife toma medidas razonables para asegurarse que la información sea manejada de manera confidencial y para los propósitos para los cuales fue compartida, sin embargo, le informamos que cada distribuidor actúa individualmente como responsable de la información que ha recibido.</p>
        <p class="text-justify stylesh-font15">En caso de estar inscrito como distribuidor, le informamos que la información relativa a sus estadísticas de compra y venta son compartidas con su presentador, lo cual fue establecido en el respectivo contrato; lo anterior para brindar los medios necesarios en el desarrollo del esquema de negocio de cada distribuidor. Dicha información se considera confidencial y cada distribuidor se obliga a cumplir con lo dispuesto en las leyes aplicables.</p>
        <p class="text-justify stylesh-font15">Podríamos emplear intermediarios para desempeñar funciones de parte nuestra. Ejemplos de dichas funciones incluyen envío de pedidos, procesamiento de pagos por tarjetas de crédito/débito, servicio al cliente y análisis de mercado. Estos intermediarios se encuentran bajo obligación de contrato para usar los datos confidenciales que reciban de Omnilife únicamente para los propósitos que quepan dentro de las funciones para las cuáles sean contratados.</p>',
    'part5' => '<p class="text-justify stylesh-font15"><b>¿CÓMO PUEDE ACCEDER, RECTIFICAR O CANCELAR SUS DATOS PERSONALES, U OPONERSE A SU USO?</b></p>
        <p class="text-justify stylesh-font15">Omnilife ha designado como responsable de la custodia, control y gestión de sus datos al Departamento de Protección de Datos Personales, quien realizará acciones para garantizar y salvaguardar sus derechos, así como para velar por el cumplimiento de los principios de protección de datos personales establecidos por las Leyes aplicables.</p>        
        <p class="text-justify stylesh-font15">Usted tiene derecho a conocer qué datos personales tenemos de usted, para qué los utilizamos y las condiciones del uso que les damos (Acceso). Asimismo, es su derecho solicitar la corrección de su información personal en caso de que esté desactualizada, sea inexacta o incompleta (Rectificación); que la eliminemos de nuestros registros o bases de datos cuando considere que la misma no está siendo utilizada adecuadamente (Cancelación); así como oponerse al uso de sus datos personales para fines específicos (Oposición). Estos derechos los denominamos derechos ARCO.</p>
        
        <p class="text-justify stylesh-font15">Para el ejercicio de cualquiera de los derechos “ARCO” favor de seguir las instrucciones detalladas a continuación:</p>
        <ol class="text-justify stylesh-font15"> 
            <li> El titular de la información deberá dar click en el vínculo titulado “Solicitud de Derechos ARCO”.</li>
            <li> Favor de imprimir y llenar los campos que allí se especifican.</li>
            <li> Una vez hecho este procedimiento, escanear y enviar la solicitud al correo electrónico: privacidad@omnilife.com</li>
        </ol>
        <p class="text-justify stylesh-font15">Para poder dar respuesta a su solicitud, el escrito deberá ir acompañado por copia de una identificación oficial del titular de la información, o en su caso carta poder del representante legal, así como cualquier otro documento relacionado a la petición. Los tiempos de respuesta serán acordes a los estipulados en la Ley.</p>',
    'part6' => '<p class="text-justify stylesh-font15"><b>USTED PUEDE REVOCAR SU CONSENTIMIENTO PARA EL USO DE SUS DATOS PERSONALES Y LIMITAR EL USO O DIVULGACIÓN DE SU INFORMACIÓN PERSONAL</b></p>
        <p class="text-justify stylesh-font15">Usted puede revocar el consentimiento que, en su caso, nos haya otorgado para el tratamiento de sus datos personales. Sin embargo, es importante que tenga en cuenta que no en todos los casos podremos atender su solicitud o concluir el uso de forma inmediata, ya que es posible que por alguna obligación legal requiramos seguir tratando sus datos personales. Asimismo, usted deberá considerar que para ciertos fines, la revocación de su consentimiento implicará que no le podamos seguir prestando el servicio que nos solicitó, o la conclusión de su relación con nosotros.</p>
        <p class="text-justify stylesh-font15">Con objeto de que pueda:</p>
        <ul class="stylesh-font15">
            <li>	Limitar el uso y divulgación de su información personal, le ofrecemos el registro en el listado de exclusión a fin de que sus datos personales no sean tratados para fines mercadotécnicos, publicitarios, o de prospección comercial por nuestra parte o</li>
            <li>	Revocar su consentimiento.</li>
        </ul>
        <p class="text-justify stylesh-font15">Usted deberá presentar su “Solicitud de Derechos ARCO” mencionada en el apartado anterior, a través del siguiente correo electrónico: privacidad@omnilife.com</p>',
    'part7' => '<p class="text-justify stylesh-font15"><b>EL USO DE TECNOLOGÍAS DE RASTREO EN NUESTRO PORTAL DE INTERNET</b></p>
        <p class="text-justify stylesh-font15">Le informamos que en nuestra página de internet utilizamos cookies, web beacons u otras tecnologías, a través de las cuales es posible monitorear su comportamiento como usuario de internet, así como brindarle un mejor servicio y experiencia al navegar en nuestra página. Los datos personales que recabamos a través de estas tecnologías, los utilizaremos para los siguientes fines:</p>
        <ul class="stylesh-font15">
            <li>	Análisis y estadística.</li>
            <li>	Para proveer servicios y productos de acuerdo a sus intereses.</li>
            <li>	Fines publicitarios.</li>
        </ul>
        <p class="text-justify stylesh-font15">Los datos personales que obtenemos de estas tecnologías de rastreo son los siguientes:</p>
        <ul class="stylesh-font15">
            <li>	Identificadores, nombre de usuario y contraseñas de una sesión.</li>
            <li>	Idioma preferido por el usuario.</li>
            <li>	Región en la que se encuentra el usuario.</li>
            <li>	Búsquedas realizadas por un usuario.</li>
            <li>	Publicidad revisada por un usuario.</li>
            <li>	Listas y hábitos de consumo en páginas de compras.</li>
        </ul>
        <p class="text-justify stylesh-font15">Para conocer la forma en que se pueden deshabilitar estas tecnologías, consulte con su proveedor de navegación web o comuníquese a nuestras líneas de atención telefónica CREO.</p>',
    'part8' => '<p class="text-justify stylesh-font15"><b>SEGURIDAD Y CUIDADO DE SUS DATOS PERSONALES</b></p>
        <p class="text-justify stylesh-font15">En Omnilife utilizamos prácticas estándares de seguridad en la industria; así como medidas con el fin de evitar la pérdida, mal uso, acceso no autorizado, divulgación o alteración de la información. No guardamos datos personales más de lo necesario para cumplir con el fin por el cual dichos datos fueron recabados, a menos que por razones contractuales, legales o regulatorias, se requiera que la información personal sea eliminada por períodos de tiempo determinados.</p>
        <p class="text-justify stylesh-font15">No obstante lo anterior, Omnilife no será responsable por ataques informáticos y en general cualquier acción que tenga como objetivo infringir las medidas de seguridad establecidas para la protección de los datos personales e información diferente a estos contenida en sus equipos informáticos o en aquellos contratados con terceros. En caso de que esto suceda, Omnilife se lo informará oportunamente para que usted pueda tomar las medidas cautelares respectivas.</p>',
    'part9' => '<p class="text-justify stylesh-font15"><b>¿CÓMO PUEDE CONOCER LOS CAMBIOS EN NUESTRA POLÍTICA DE PRIVACIDAD?</b></p>
        <p class="text-justify stylesh-font15">Nuestra política de privacidad puede sufrir modificaciones, cambios o actualizaciones derivadas de nuevos requerimientos legales; de nuestras propias necesidades por los productos o servicios que ofrecemos; de nuestras prácticas de privacidad; de cambios en nuestro modelo de negocio, o por otras causas.</p>
        <p class="text-justify stylesh-font15">Nos comprometemos a mantenerlo informado sobre estos cambios, los cuales se publicarán a través del sitio web oficial de Omnilife correspondiente a su país, en su apartado denominado “Política de Privacidad” o en caso de ser necesario se lo comunicaremos por cualquiera de los medios de contacto que nos haya proporcionado.</p>
        <p class="text-right stylesh-font15">Fecha de actualización: 22 de enero del  2018</p>',
    'part10' => '<p class="text-justify stylesh-font15"><b>CONTÁCTENOS</b></p>
        <p class="text-justify stylesh-font15">Si usted tiene preguntas o preocupaciones con respecto a su privacidad, por favor póngase en contacto con nosotros, a través de: <span class="products-colorViolet">privacidad@omnilife.com</span>  o comunicándose a nuestras líneas de atención telefónica correspondiente a su país, será un placer atenderlo: <span class="products-colorViolet">https://www.omnilife.com/respaldo-omnilife/</span></p>',
    'part11'=> '<p class="text-justify stylesh-font13 products-colorGray">* Los términos aquí utilizados son genéricos, los mismos pueden variar dependiendo el país y la relación que usted mantenga con alguna de las empresas miembro del Grupo Omnilife. Para conocer bajo que conceptos se encuentra regulada su relación, favor de consultarlo en nuestros centros de atención telefónica. La presente política de privacidad no establece los términos utilizados en nuestro esquema de negocio.</p>
        <p class="text-justify stylesh-font13 products-colorGray">El responsable de la protección y tratamiento de sus datos personales capturados en internet y vía telefónica, es Grupo Omnilife, S.A. de C.V. , sociedad localizada en el país de México. En caso de que usted proporcione información de manera presencial en alguno de nuestros centros de atención/establecimientos/instalaciones, el responsable de la protección de sus datos personales podría variar dependiendo el país donde usted se localice y la relación que mantenga con alguna de las empresas miembro del Grupo Omnilife, ello se le informará oportunamente en el lugar donde se recaben sus datos; sin embargo las políticas de privacidad en los distintos países donde tenemos presencia se rigen bajo los mismos principios, medidas de seguridad y confidencialidad que se establecen en la presente política de privacidad, por lo que puede tener la tranquilidad de que su información estará debidamente resguardada.</p>'
];