<?php

return [

    'title' => 'Términos and Condiciones',
    'part1' => '<p class="text-justify stylesh-font15">Gracias por visitar https://www.omnilife.com/ . Este sitio web (<b class="products-colorGreen ">Nfuerza</b>) es un servicio proporcionado por el Grupo Omnilife, S.A. de C.V. y sus empresas subsidiarias (“Omnilife”) para facilitar la compra de los productos, programas y servicios de Omnilife y el acceso a éstos. Todo contenido, información y servicio proporcionado en el Sitio y a través de éste puede utilizarse sólo de acuerdo con los siguientes términos y condiciones (los “Términos de uso”).</p>
        <p class="text-justify stylesh-font15">SU USO DE ESTE SITIO CONSTITUYE SU ACEPTACIÓN DE ESTAR REGIDO POR LOS SIGUIENTES TÉRMINOS DE USO, CON LAS POSIBLES MODIFICACIONES QUE REALICE OCASIONALMENTE OMNILIFE. LÉALOS ATENTAMENTE ANTES DE UTILIZAR EL SITIO. SI NO ESTÁ DE ACUERDO CON ALGUNA PARTE DE ESTOS TÉRMINOS DE USO, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO.</p>',
    'part2' => '<p class="text-justify stylesh-font15"><b>Licencia de usuario </b></p>
        <p class="text-justify stylesh-font15">Se le otorga una licencia limitada, no exclusiva e intransferible para acceder al Sitio y a su contenido de acuerdo con estos Términos de uso. Si es menor de 18 años, sólo podrá utilizar el Sitio con la participación de un padre o tutor. El Sitio está alojado en México, pero contiene información general que es adecuada para el acceso y el uso global. Omnilife no hace declaración alguna con respecto a que todos los materiales del Sitio son adecuados o están disponibles para el uso fuera de México, y está prohibido acceder a estos materiales desde territorios en los que su contenido es ilegal. El Sitio puede contener referencias o referencias cruzadas a productos, programas o servicios que no han sido publicitados o que no están disponibles en su país, y dichas referencias no implican que Omnilife tenga planificado publicitar o poner a disposición dichos productos, programas o servicios en su país. Consulte a su contacto local de Omnilife para obtener información relacionada con los productos, programas y servicios disponibles para usted o, si accede a este Sitio desde otros lugares, puede elegir seguir el enlace a un sitio web afiliado donde encontrará información relacionada con disponibilidad, reclamos y comparaciones de productos, programas y servicios correspondientes al lugar donde usted se encuentre (Consulte Enlaces a sitios web afiliados, a continuación). Aquellos que accedan a este Sitio desde otros lugares lo hacen por iniciativa propia y son responsables de cumplir con las leyes locales, que incluyen las leyes relacionadas con la transmisión de datos técnicos exportados de México o del territorio en el que residen.</p>
        <p class="text-justify stylesh-font15">Omnilife se reserva el derecho a rechazar el servicio a su absoluta discreción y sin previo aviso. Usted es el único responsable de su uso del Sitio y acepta compensar, exonerar y defender a Omnilife de todo reclamo, daño, pérdida, responsabilidad, costo y gasto, incluidos los honorarios de abogados, que resulten de su uso o mal uso del Sitio. Está estrictamente prohibida la publicación o transmisión de material ilegal, amenazador, calumnioso, difamatorio, obsceno, indecente, incendiario, pornográfico o profano, o de cualquier material que pudiera constituir o fomentar una conducta que pueda considerarse una ofensa criminal, dar lugar a responsabilidades civiles o de algún otro modo infringir alguna ley.</p>',
    'part3' => '<p class="text-justify stylesh-font15"><b>Limitaciones en su uso </b></p>
        <p class="text-justify stylesh-font15">Ningún material del Sitio de Omnilife puede ser utilizado, copiado, reproducido, republicado, descargado, publicado, mostrado, transmitido o distribuido de ninguna manera, sin la autorización previa por escrito de Omnilife, excepto que usted puede descargar una copia de los materiales en una única computadora sólo para su uso personal, no comercial y privado, siempre y cuando (i) mantenga intactos todos los avisos de propiedad intelectual y otros avisos de privacidad, y (ii) no realice modificaciones a los materiales. No está permitido, sin el permiso previo por escrito de Omnilife, enmarcar o replicar ningún material contenido en este Sitio en ningún otro servidor. Está expresamente prohibido el uso no autorizado de dicho material en ningún otro entorno informático o sitio web.</p>',
    'part4' => '<p class="text-justify stylesh-font15"><b>Privacidad e información personal</b></p>
        <p class="text-justify stylesh-font15">Su uso del Sitio también está sujeto a los términos de la Política de Privacidad. Usted reconoce que ha leído y que comprende la Política de privacidad, y acepta el uso de toda información personal que usted proporcione de acuerdo con los términos de la Política de privacidad y para los fines establecidos en ésta.</p>',
    'part5' => '<p class="text-justify stylesh-font15"><b>Derechos de propiedad intelectual </b></p>
        <p class="text-justify stylesh-font15">Derechos de autor: el diseño, el código de fuente, la programación, la estructura de navegación, las bases de datos, el texto, el contenido, la selección y la disposición de los elementos, la organización, los gráficos, las fotografías, las imágenes, la compilación, la traducción magnética, la conversión digital y todos los demás elementos contenidos en el Sitio y los asuntos relacionados con el Sitio (en forma colectiva, los “Elementos”) están protegidos por las leyes de derecho de autor y los tratados internacionales correspondientes. La publicación de alguno de estos Elementos en el Sitio no constituye la renuncia a ningún derecho en dichos Elementos, y no confiere ninguna licencia ni transferencia de derechos de ningún tipo en relación con éstos. Salvo que se exprese lo contrario en este documento, ningún Elemento puede ser utilizado, copiado, reproducido, descargado, publicado, mostrado, transmitido, modificado o distribuido de ninguna forma ni por ningún medio, entre los que se incluyen, medios electrónicos, medios mecánicos, fotocopia, grabación u otro, sin el permiso previo por escrito de Omnilife.</p>
        <p class="text-justify stylesh-font15">Marca comercial: Omnilife®, el logotipo, y todos los nombres de productos, los nombres de compañías y otras marcas comerciales y logotipos incluidos en el Sitio, a menos que se especifique lo contrario, son marcas comerciales o imágenes comerciales de Omnilife (en forma colectiva, las “Marcas”) y están protegidas por las leyes y los tratados internacionales correspondientes. Todos los demás nombres de productos, marcas comerciales, nombres de compañías, logotipos, marcas de servicio o imágenes comerciales mencionados, exhibidos, citados o de algún otro modo indicados en el Sitio son propiedad de sus respectivos dueños. La publicación de las Marcas en el Sitio no constituye la renuncia a ningún derecho en dichas Marcas, y no confiere ninguna licencia ni transferencia de derechos de ningún tipo en relación con éstas.</p>
        <p class="text-justify stylesh-font15">Los Elementos y las Marcas son mencionados en este documento como el “material” o los “materiales”.</p>
        <p class="text-justify stylesh-font15">Está expresamente prohibido el uso y/o el mal uso de cualquiera o todos de los Elementos, las Marcas y/o cualquier otro material contenido en el Sitio, sin el permiso previo por escrito de su propietario.</p>',
    'part6' => '<p class="text-justify stylesh-font15"><b>Exención de garantía </b></p>
        <p class="text-justify stylesh-font15">EL SITIO DE OMNILIFE Y SUS CONTENIDOS SON PROPORCIONADOS “COMO ESTA” Y “COMO DISPONIBLE” SIN GARANTÍA DE NINGÚN TIPO. HASTA EL MÁXIMO DE LO PERMITIDO POR LA LEY VIGENTE, OMNILIFE RECHAZA EXPRESAMENTE TODA GARANTÍA, EXPRESA O IMPLÍCITA, INCLUIDAS ENTRE OTRAS, LAS GARANTÍAS DE COMERCIABILIDAD, APTITUD PARA UN FIN DETERMINADO Y NO CONTRAVENCIÓN, Y LAS QUE SURJAN POR ESTATUTO O DE ALGÚN OTRO MODO POR LEY O POR EL CURSO DE LAS TRANSACCIONES O EL USO COMERCIAL. OMNILIFE NO HACE NINGUNA DECLARACIÓN NI OFRECE GARANTÍA DE NINGÚN TIPO CON RESPECTO A LA EXHAUSTIVIDAD LA EXACTITUD, LA CORRECCIÓN, INTEGRIDAD, LA CONFIABILIDAD, LA ACTUALIDAD, LA ADECUACIÓN, LA IDONEIDAD, LA FUNCIONALIDAD, LA DISPONIBILIDAD O EL FUNCIONAMIENTO DE ESTE SITIO O DEL CONTENIDO O LOS SERVICIOS PROPORCIONADOS EN EL SITIO O ACCESIBLES A TRAVÉS DE ÉSTE. OMNILIFE NO GARANTIZA QUE EL FUNCIONAMIENTO DE ESTE SITIO SERÁ ININTERRUMPIDO O SIN ERRORES, O QUE ESTE SITIO ESTÁ LIBRE DE VIRUS O DE OTROS COMPONENTES DAÑINOS PARA EL EQUIPO O EL SOFTWARE.</p>',
    'part7' => '<p class="text-justify stylesh-font15"><b>Limitación de responsabilidad </b></p>
        <p class="text-justify stylesh-font15">EN NINGÚN CASO OMNILIFE DEBERÁ RENDIR CUENTAS NI ASUME RESPONSABILIDAD POR NINGÚN DAÑO DIRECTO, INDIRECTO, ESPECIAL, FORTUITO O DERIVADO QUE SE PRODUZCA POR EL USO O LA INCAPACIDAD DE USO DE ESTE SITIO (O EL CONTENIDO O LOS SERVICIOS PROPORCIONADOS EN EL SITIO O ACCESIBLES A TRAVÉS DE ÉSTE) O EN CONEXIÓN CON ÉSTE, O DE ALGÚN OTRO MODO, INCLUSO SI SE LE HA ADVERTIDO A OMNILIFE SOBRE LA POSIBILIDAD DE DICHOS DAÑOS.</p>',
    'part8' => '<p class="text-justify stylesh-font15"><b>Errores y correcciones </b></p>
        <p class="text-justify stylesh-font15">Si bien Omnilife realiza esfuerzos razonables para incluir información precisa y actualizada en el Sitio, Omnilife no garantiza ni declara que el Sitio estará libre de errores. Los errores en el ingreso de datos y otros problemas técnicos en ocasiones pueden hacer que se muestre información inexacta. Omnilife se reserva el derecho a corregir cualquier inexactitud o error tipográfico en el Sitio, y no será responsable por dichos errores. Omnilife también puede realizar mejoras y/o cambios en las aplicaciones, la funcionalidad o el contenido del Sitio en cualquier momento. Si observa alguna información o descripción que considera incorrecta, comuníquese con nosotros según se describe en la sección “Contacto”, y Omnilife la verificará por usted.</p>',
    'part9'=> '<p class="text-justify stylesh-font15"><b>Enlaces a sitios web afiliados</b></p>
        <p class="text-justify stylesh-font15">El Sitio de Omnilife contiene enlaces a sitios web afiliados, los cuales le permiten recibir información específica en relación con la disponibilidad, los reclamos y las comparaciones de productos correspondientes al lugar donde usted vive. Los afiliados son responsables de que sus propios sitios web cumplan con las leyes vigentes en sus respectivas jurisdicciones, y se comprometen a revisarlos. Estos enlaces se proporcionan sólo para ofrecerle mayor conveniencia. Omnilife no aprueba ni acepta ninguna responsabilidad por el contenido de un sitio web afiliado o por la accesibilidad de los recursos disponibles en éstos. Omnilife le sugiere que revise cuidadosamente los términos de uso de cada sitio web afiliado al que elija acceder desde el Sitio.</p>',
    'part10'=> '<p class="text-justify stylesh-font15"><b>Presentaciones</b></p>
        <p class="text-justify stylesh-font15">Omnilife se complace en escuchar a los usuarios del Sitio y agradece sus comentarios con respecto a los contenidos y los servicios. Toda información que no sea de identificación personal, la cual se trata en la Política de privacidad del Sitio, cualquier sugerencia, idea, concepto, material u otra información que usted envíe a este Sitio o a través de éste (“Presentaciones”) se convertirá de forma permanente en propiedad exclusiva de Omnilife. Omnilife no tendrá obligación de ningún tipo con respecto a dichas Presentaciones y será libre de utilizar y divulgar las Presentaciones a otros sin limitación.</p>',
    'part11'=> '<p class="text-justify stylesh-font15"><b>Legislación y jurisdicción vigentes</b></p>
        <p class="text-justify stylesh-font15">Estos Términos de uso son regidos por las leyes de México y se interpretan de acuerdo con estas leyes, sin dar efecto a ningún principio de conflictos de leyes. Cualquier controversia o disputa que surja de su uso del Sitio deberá enviarse a la jurisdicción personal de cualquier tribunal estatal o federal ubicado en México, lo cual usted acepta irrevocablemente. Si se determina que alguna disposición de estos Términos de uso es ilegal, nula o por algún motivo inexigible, dicha disposición se eliminará y no afectará la validez y la aplicabilidad de las disposiciones restantes.</p>',
    'part12'=> '<p class="text-justify stylesh-font15"><b>Cambios en el Sitio y en los Términos de uso</b> </p>
        <p class="text-justify stylesh-font15">Omnilife se reserva el derecho, a su absoluta discreción, a cambiar el Sitio y/o su contenido y estos Términos de uso en cualquier momento, sin previo aviso. Las versiones actualizadas de los Términos de uso se publicarán en el Sitio y serán efectivas inmediatamente. La fecha de la última versión se indica a continuación. Contrólela con frecuencia, especialmente antes de utilizar el Sitio, para saber si estos Términos de uso han cambiado. El uso continuado del Sitio después de cualquier cambio en los Términos de uso constituye su consentimiento a dichos cambios.</p>',

];